# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Vincentqyw"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

keywords:
    "QRCode": 
        filters:["Multi QRCode", "QRCode segmintation"]
    "bar code":
        filters: ["Multi barcode", "barCode segmintation"]
