# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "yourfather"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 100

publish_readme: True
publish_gitpage: True
publish_wechat: False

keywords:
    "QRCode": 
        filters: ["Multi QRCode", "QRCode segmintation"]
    "BarCode":
        filters: ["Multi BarCode", "BarCode segmintation"]
